//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitacoraCoachingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso_usuario
    {
        public int idp { get; set; }
        public int Proceso_id_proceso { get; set; }
        public int Usuario_id_usuario { get; set; }
    
        public virtual Proceso Proceso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
