//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitacoraCoachingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proceso()
        {
            this.Proceso_usuario = new HashSet<Proceso_usuario>();
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int id_proceso { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public string indicador_exito { get; set; }
        public string plan_accion { get; set; }
        public string objetivo_proceso { get; set; }
        public int cantidad_sesion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proceso_usuario> Proceso_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesion> Sesion { get; set; }
    }
}
