//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitacoraCoachingV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Proceso_usuario = new HashSet<Proceso_usuario>();
        }
    
        public int id_usuario { get; set; }
        public string email_usuario { get; set; }
        public string pass_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string fono_usuario { get; set; }
        public string cargo_usuario { get; set; }
        public int Rol_id_rol { get; set; }
        public Nullable<int> Empresa_id_empresa { get; set; }
        public Nullable<int> Jefe_id_jefe { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Jefe Jefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proceso_usuario> Proceso_usuario { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
